### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/noa-for-android#1]
- [x] Print the chatGPT error directly as you receive it. No need to wrap it
- [x] Remove the "res" from the chat bubble
- [x] Follow the Figma exactly for the "Not Connected" message. Correct capitalisation and icon included
- [x] Match all the colors to the Figma design
- [x] Make the settings gear icon slightly smaller and align it a little better
- [x] Remove the grey background box, and make the background color exactly the same as the Figma design
- [x] Reduce the gap between the chat bubbles

**Comment by rohitrathnam** [comment]
Main page
- [ ] Settings gear is still android green vs teal
- [ ] Top bar could use equal vertical padding (now its bigger top)
![image](https://github.com/brilliantlabsAR/argpt-for-android/assets/22655874/2ceb40cd-615b-4d8c-9177-7bebcc9b894f)
- [ ] App disconnects from monocle when my screen turns off, but device is not locked, there should be a way to make it stay connected / prevent screen from sleeping
- [ ] Prompts get sent twice after disconnect / reconnect

Settings menu
- [ ] Inside the settings menu the top padding is smaller than the bottom padding
- [x] There's no horizontal padding applied on the grey divider
- [ ] The trailing (right) margin of the settings pop up doesn't respect the rest of the page padding rule
- [ ] Settings pop up is also weirdly far from the top bar
- [x] The background of that pop up is beige idk if that's supposed to be that colour or matching light grey like the chat box
- [x] Probably want to change the settings popup size to fit the content or the screen, there's a bunch of trailing space
![image](https://github.com/brilliantlabsAR/argpt-for-android/assets/22655874/63fc0bc8-8a76-4c49-811b-7cd8899e1804)
- [ ] The toast messages (like 'monocle connected') follow my device theme but the 'turn on gps / turn on bluetooth' doesn't, would be nice to have it all in light theme / white for now until we implement dark theme
![image](https://github.com/brilliantlabsAR/argpt-for-android/assets/22655874/185fef24-8c1c-4eee-9f02-fe2f99cc492c)
- [x] Think there's no point of a 'no' button to this pop up because the app can't be used without it, better off saying something like "Please turn on X (OK)"
![image](https://github.com/brilliantlabsAR/argpt-for-android/assets/22655874/b08d95cf-57d8-4ef2-b206-1ed464ee6666)
- [ ] Tapping the background of the turn on bluetooth goes to a blank screen, need to force quit to make it work after that
![image](https://github.com/brilliantlabsAR/argpt-for-android/assets/22655874/11fcafc3-7c30-4525-8816-b71cad29b94e)

**Comment by siliconwitch** [comment]
@Nigtwing These are all the current issues from the build you sent: 8th Aug 17:31

- [x] Privacy Policy & T&Cs links don't work
- [x] Tapping outside the "Bluetooth is disabled" popup still results in an empty screen
- [x] App connecting to other Monocles instead of the one it was originally paired to
- [x] Remove toast messages
- [x] API key box buttons should be "Done" and "Get Key"
- [x] App sometimes doesn't reconnect after Monocle wakes up from sleep
- [x] App doesn't reconnect when in background or locked
